// 楽曲データ管理 
// KOMOREBI: LinkCoreを3mY4fgvVtに統一（official同期用メタ更新）
// SOW仕様: 検索・ソート機能対応のデータ構造

const songsData = {
  // OMOKAGE
  owaranaiuta: {
    title: '終わらない歌',
    reading: 'おわらないうた',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/owaranaiuta?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 12,
  },
  nagaimichi: {
    title: '長い道',
    reading: 'ながいみち',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/nagaimichi?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 11,
  },
  arukidasumiraihe: {
    title: '歩き出す未来へ',
    reading: 'あるきだすみらいへ',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/arukidasumiraihe?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 10,
  },
  doredakesugitemo: {
    title: 'どれだけ過ぎても',
    reading: 'どれだけすぎても',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/doredakesugitemo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 9,
  },
  kiminiaitaiyo: {
    title: '君に逢いたいよ',
    reading: 'きみにあいたいよ',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminiaitaiyo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 8,
  },
  kimiwoomotabi: {
    title: '君を想うたび',
    reading: 'きみをおもうたび',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimiwoomotabi?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 7,
  },
  aenaijikan: {
    title: '逢えない時間',
    reading: 'あえないじかん',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/aenaijikan?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 6,
  },
  naminokioku: {
    title: '波の記憶',
    reading: 'なみのきおく',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/naminokioku?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 5,
  },
  kienaioto: {
    title: '消えない音',
    reading: 'きえないおと',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kienaioto?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 4,
  },
  saigonosansetto: {
    title: '最後のサンセット',
    reading: 'さいごのさんせっと',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/saigonosansetto?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 3,
  },
  madakokoni: {
    title: 'まだここに',
    reading: 'まだここに',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/madakokoni?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 2,
  },
  kiminokomoriuta: {
    title: '君の子守唄',
    reading: 'きみのこもりうた',
    album: 'OMOKAGE',
    albumReading: 'おもかげ',
    releaseDate: '2026-06-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminokomoriuta?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 1,
  },
  // kagayaki
  negaiwodakishimete: {
    title: '願いを抱きしめて',
    reading: 'ねがいをだきしめて',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/negaiwodakishimete?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 15,
  },
  harugakitemo: {
    title: '春が来ても',
    reading: 'はるがきても',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/harugakitemo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 14,
  },
  kimiwoushinattekara: {
    title: '君を失ってから',
    reading: 'きみをうしなってから',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimiwoushinattekara?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 13,
  },
  negainegau: {
    title: '願い願う',
    reading: 'ねがいねがう',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/negainegau?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 12,
  },
  soresurakanawanai: {
    title: 'それすら叶わない',
    reading: 'それすらかなわない',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/soresurakanawanai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 11,
  },
  onajisoranoiro: {
    title: '同じ空の色',
    reading: 'おなじそらのいろ',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/onajisoranoiro?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 10,
  },
  mouichidokimito: {
    title: 'もう一度君と',
    reading: 'もういちどきみと',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/mouichidokimito?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 9,
  },
  kienaimamaharu: {
    title: '消えないまま春',
    reading: 'きえないままはる',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kienaimamaharu?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 8,
  },
  madakimiwoomotteru: {
    title: 'まだ君を想ってる',
    reading: 'まだきみをおもってる',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/madakimiwoomotteru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 7,
  },
  namaedemoyobenai: {
    title: '名前でも呼べない',
    reading: 'なまえでもよべない',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namaedemoyobenai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 6,
  },
  kiminiainiikuyo: {
    title: '君に会いに行くよ',
    reading: 'きみにあいにいくよ',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminiainiikuyo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 5,
  },
  donnamiraigamatteitemo: {
    title: 'どんな未来が待っていても',
    reading: 'どんなみらいがまっていても',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/donnamiraigamatteitemo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 4,
  },
  kiminotokorohe: {
    title: '君のところへ',
    reading: 'きみのところへ',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminotokorohe?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 3,
  },
  tsutaetaikotobaha: {
    title: '伝えたい言葉は',
    reading: 'つたえたいことばは',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/tsutaetaikotobaha?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 2,
  },
  saigonosakura: {
    title: '最後の桜',
    reading: 'さいごのさくら',
    album: 'kagayaki',
    albumReading: 'かがやき',
    releaseDate: '2026-03-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/saigonosakura?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 1,
  },
  // IROZUKI
  namidaganagaretemo: {
    title: '涙が流れても',
    reading: 'なみだがながれても',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namidaganagaretemo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 15,
  },
  soredemokimiwoshinjitai: {
    title: 'それでも君を信じたい',
    reading: 'それでもきみをしんじたい',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/soredemokimiwoshinjitai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 14,
  },
  namaewoyobanaiyoru: {
    title: '名前を呼ばない夜',
    reading: 'なまえをよばないよる',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namaewoyobanaiyoru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 13,
  },
  onajibashode: {
    title: '同じ場所で',
    reading: 'おなじばしょで',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/onajibashode?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 12,
  },
  itsukakanashimigaomoideninarumade: {
    title: 'いつか悲しみが思い出になるまで',
    reading: 'いつかかなしみがおもいでになるまで',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/itsukakanashimigaomoideninarumade?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 11,
  },
  tsumugu: {
    title: '紡ぐ',
    reading: 'つむぐ',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/tsumugu?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 10,
  },
  bokunonakade: {
    title: '僕の中で',
    reading: 'ぼくのなかで',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/bokunonakade?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 9,
  },
  bokunosenakanitsubasagaareba: {
    title: '僕の背中に翼があれば',
    reading: 'ぼくのせなかにつばさがあれば',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/bokunosenakanitsubasagaareba?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 8,
  },
  darekawosasaeteru: {
    title: '誰かを支えてる',
    reading: 'だれかをささえてる',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/darekawosasaeteru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 7,
  },
  zuttoisshoni: {
    title: 'ずっと一緒に',
    reading: 'ずっといっしょに',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/zuttoisshoni?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 6,
  },
  kimigakuretahikari: {
    title: '君がくれた光',
    reading: 'きみがくれたひかり',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimigakuretahikari?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 5,
  },
  anatawoomou: {
    title: 'あなたを想う',
    reading: 'あなたをおもう',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/anatawoomou?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 4,
  },
  sunaoniienakute: {
    title: '素直に言えなくて',
    reading: 'すなおにいえなくて',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/sunaoniienakute?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 3,
  },
  imawoterashiteru: {
    title: '今を照らしてる',
    reading: 'いまをてらしてる',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/imawoterashiteru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 2,
  },
  anatanotonarini: {
    title: 'あなたの隣に',
    reading: 'あなたのとなりに',
    album: 'IROZUKI',
    albumReading: 'いろずき',
    releaseDate: '2026-01-30',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/anatanotonarini?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 1,
  },
  fuyunokiseki: {
    title: '冬の奇跡',
    reading: 'ふゆのきせき',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/fuyunokiseki?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 15,
  },
  yuki: {
    title: '雪',
    reading: 'ゆき',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/yuki?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 14,
  },
  wasurenai: {
    title: '忘れない',
    reading: 'わすれない',
    album: 'TOKOSHIE / KONAYUKI',
    albumReading: 'とこしえ / こなゆき',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/wasurenai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 15,
  },
  naiteiikara: {
    title: '泣いていいから',
    reading: 'ないていいから',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/naiteiikara?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 12,
  },
  mouichido: {
    title: 'もう一度',
    reading: 'もういちど',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/mouichido?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 11,
  },
  kimihe: {
    title: '君へ',
    reading: 'きみへ',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimihe?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 10,
  },
  stillinmyheart: {
    title: 'Still in my heart',
    reading: 'すてぃる いん まい はーと',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/stillinmyheart?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 9,
  },
  konosakinomirai: {
    title: 'この先の未来に',
    reading: 'このさきのみらいに',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/konosakinomirai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 8,
  },
  kanarazususumeru: {
    title: '必ず進める',
    reading: 'かならずすすめる',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kanarazususumeru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 7,
  },
  kokoroniitsumademo: {
    title: '心にいつまでも',
    reading: 'こころにいつまでも',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kokoroniitsumademo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 6,
  },
  kimigainaisekai: {
    title: '君が居ない世界',
    reading: 'きみがいないせかい',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimigainaisekai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 5,
  },
  aitakute: {
    title: '会いたくて',
    reading: 'あいたくて',
    album: 'TOKOSHIE / KONAYUKI',
    albumReading: 'とこしえ / こなゆき',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/aitakute?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 2,
  },
  dakaraimagaaru: {
    title: 'だから今がある',
    reading: 'だからいまがある',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/dakaraimagaaru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 3,
  },
  kienaiakari: {
    title: '消えない灯り',
    reading: 'きえないあかり',
    album: 'KONAYUKI',
    albumReading: 'こなゆき',
    releaseDate: '2025-12-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kienaiakari?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 2,
  },
  saigonoyuki: {
    title: '最後の雪',
    reading: 'さいごのゆき',
    album: 'TOKOSHIE / KONAYUKI',
    albumReading: 'とこしえ / こなゆき',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/saigonoyuki?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 11,
  },
  inochi: {
    title: 'いのちの理由',
    reading: 'いのちのりゆう',
    album: '',
    albumReading: '',
    releaseDate: '2025-06-10',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/inochi?utm_source=appriver.jp&utm_medium=referral',
  },
  kage: {
    title: '君の影',
    reading: 'きみのかげ',
    album: '',
    albumReading: '',
    releaseDate: '2025-06-11',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kage?utm_source=appriver.jp&utm_medium=referral',
  },
  todokanai: {
    title: '届かない・・',
    reading: 'とどかない',
    album: 'TOKOSHIE',
    albumReading: 'とこしえ',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/todokanai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 5,
  },
  kimitointajikan: {
    title: '君といた時間',
    reading: 'きみといたじかん',
    album: 'TOKOSHIE',
    albumReading: 'とこしえ',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimitointajikan?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 13,
  },
  kokoro: {
    title: '心の羽',
    reading: 'こころのはね',
    album: '',
    albumReading: '',
    releaseDate: '2025-07-08',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kokoro?utm_source=appriver.jp&utm_medium=referral',
  },
  yasashii: {
    title: '優しい光(Remix)',
    reading: 'やさしいひかりりみっくす',
    album: 'TOKOSHIE / NUKUMORI',
    albumReading: 'とこしえ / ぬくもり',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/yasashii?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 1,
  },
  moshi: {
    title: 'もし',
    reading: 'もし',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/moshi?utm_source=appriver.jp&utm_medium=referral',
  },
  imanani: {
    title: '今何してるだろう',
    reading: 'いまなにしてるだろう',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/imanani?utm_source=appriver.jp&utm_medium=referral',
  },
  kimidake: {
    title: '君だけのうた',
    reading: 'きみだけのうた',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimidake?utm_source=appriver.jp&utm_medium=referral',
  },
  namidaga: {
    title: '涙が',
    reading: 'なみだが',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namidaga?utm_source=appriver.jp&utm_medium=referral',
  },
  konomama: {
    title: 'このままずっと',
    reading: 'このままずっと',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/konomama?utm_source=appriver.jp&utm_medium=referral',
  },
  mienai: {
    title: '見えない光',
    reading: 'みえないひかり',
    album: 'TOKOSHIE / NUKUMORI',
    albumReading: 'とこしえ / ぬくもり',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/mienai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 10,
  },
  yumedeshika: {
    title: '夢でしか',
    reading: 'ゆめでしか',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/yumedeshika?utm_source=appriver.jp&utm_medium=referral',
  },
  bokunomichi: {
    title: '僕の道は',
    reading: 'ぼくのみちは',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/bokunomichi?utm_source=appriver.jp&utm_medium=referral',
  },
  subete: {
    title: '全てなくしても',
    reading: 'すべてなくしても',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/subete?utm_source=appriver.jp&utm_medium=referral',
  },
  sabishikute: {
    title: '寂しくて',
    reading: 'さびしくて',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/sabishikute?utm_source=appriver.jp&utm_medium=referral',
  },
  kibou: {
    title: '希望へ',
    reading: 'きぼうへ',
    album: 'TOKOSHIE / NUKUMORI',
    albumReading: 'とこしえ / ぬくもり',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kibou?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 6,
  },
  kimitoiru: {
    title: '君といる',
    reading: 'きみといる',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimitoiru?utm_source=appriver.jp&utm_medium=referral',
  },
  yumenomukou: {
    title: '夢の向こう側',
    reading: 'ゆめのむこうがわ',
    album: 'NUKUMORI',
    albumReading: 'ぬくもり',
    releaseDate: '2025-06-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/yumenomukou?utm_source=appriver.jp&utm_medium=referral',
  },
  tokiwokoete: {
    title: '時間をこえて',
    reading: 'ときをこえて',
    album: '',
    albumReading: '',
    releaseDate: '2025-07-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/tokiwokoete?utm_source=appriver.jp&utm_medium=referral',
  },
  kimiwomamoritai: {
    title: '君を守りたい',
    reading: 'きみをまもりたい',
    album: 'TOKOSHIE',
    albumReading: 'とこしえ',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimiwomamoritai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 3,
  },
  anohibi: {
    title: 'あの日々',
    reading: 'あのひび',
    album: 'TOKOSHIE',
    albumReading: 'とこしえ',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/anohibi?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 9,
  },
  modoreruna: {
    title: '戻れるなら',
    reading: 'もどれるなら',
    album: '',
    albumReading: '',
    releaseDate: '2025-07-29',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/modoreruna?utm_source=appriver.jp&utm_medium=referral',
  },
  machitsudukeru: {
    title: '待ち続ける',
    reading: 'まちつづける',
    album: '',
    albumReading: '',
    releaseDate: '2025-08-09',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/machitsudukeru?utm_source=appriver.jp&utm_medium=referral',
  },
  oresounakokoro: {
    title: '折れそうな心',
    reading: 'おれそうなこころ',
    album: '',
    albumReading: '',
    releaseDate: '2025-08-07',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/oresounakokoro?utm_source=appriver.jp&utm_medium=referral',
  },
  deaeteanakereba: {
    title: '出会えてなければ',
    reading: 'であえてなければ',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/deaeteanakereba?utm_source=appriver.jp&utm_medium=referral',
  },
  itsumademo: {
    title: 'いつまでも君を待ち続ける',
    reading: 'いつまでもきみをまちつづける',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/itsumademo?utm_source=appriver.jp&utm_medium=referral',
  },
  itooshii: {
    title: '愛おしい',
    reading: 'いとおしい',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/itooshii?utm_source=appriver.jp&utm_medium=referral',
  },
  kimidakegasubete: {
    title: '君だけが全ての世界',
    reading: 'きみだけがすべてのせかい',
    album: 'TOKOSHIE / YASURAGI',
    albumReading: 'とこしえ / やすらぎ',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimidakegasubete?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 8,
  },
  wasuretainoni: {
    title: '忘れたいのに',
    reading: 'わすれたいのに',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/wasuretainoni?utm_source=appriver.jp&utm_medium=referral',
  },
  mottohayaku: {
    title: 'もっと早くに出逢えてたなら',
    reading: 'もっとはやくにであえてたなら',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/mottohayaku?utm_source=appriver.jp&utm_medium=referral',
  },
  namidanosaki: {
    title: '涙の先',
    reading: 'なみだのさき',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namidanosaki?utm_source=appriver.jp&utm_medium=referral',
  },
  arigatouwo: {
    title: 'ありがとうを伝えたくて',
    reading: 'ありがとうをつたえたくて',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/arigatouwo?utm_source=appriver.jp&utm_medium=referral',
  },
  susumusonosaki: {
    title: '進むその先へ',
    reading: 'すすむそのさきへ',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/susumusonosaki?utm_source=appriver.jp&utm_medium=referral',
  },
  namidanohoshi: {
    title: '涙の星',
    reading: 'なみだのほし',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namidanohoshi?utm_source=appriver.jp&utm_medium=referral',
  },
  futarinosora: {
    title: 'ふたりの空へ',
    reading: 'ふたりのそらへ',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/futarinosora?utm_source=appriver.jp&utm_medium=referral',
  },
  anohitohaima: {
    title: 'あの人は今',
    reading: 'あのひとはいま',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/anohitohaima?utm_source=appriver.jp&utm_medium=referral',
  },
  kiminidetaeta: {
    title: '君に出逢えた奇跡',
    reading: 'きみにであえたきせき',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminidetaeta?utm_source=appriver.jp&utm_medium=referral',
  },
  imawoikirunda: {
    title: '今を生きるんだ',
    reading: 'いまをいきるんだ',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/imawoikirunda?utm_source=appriver.jp&utm_medium=referral',
  },
  bokunosubete: {
    title: '僕のすべて',
    reading: 'ぼくのすべて',
    album: 'YASURAGI',
    albumReading: 'やすらぎ',
    releaseDate: '2025-08-22',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/bokunosubete?utm_source=appriver.jp&utm_medium=referral',
  },
  hitoriinorudake: {
    title: '1人祈るだけ',
    reading: 'ひとりいのるだけ',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-08',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/hitoriinorudake?utm_source=appriver.jp&utm_medium=referral',
  },
  yumenokakera: {
    title: '夢のかけら',
    reading: 'ゆめのかけら',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-08',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/yumenokakera?utm_source=appriver.jp&utm_medium=referral',
  },
  naitemoii: {
    title: '泣いてもいい',
    reading: 'ないてもいい',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-08',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/naitemoii?utm_source=appriver.jp&utm_medium=referral',
  },
  kiminonamidahabokunosei: {
    title: '君の涙は僕のせい',
    reading: 'きみのなみだはぼくのせい',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-08',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminonamidahabokunosei?utm_source=appriver.jp&utm_medium=referral',
  },
  kibouwakienai: {
    title: '希望は消えない',
    reading: 'きぼうはきえない',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-08',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kibouwakienai?utm_source=appriver.jp&utm_medium=referral',
  },
  bokugamitaanosora: {
    title: '僕が見たあの空',
    reading: 'ぼくがみたあのそら',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-08',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/bokugamitaanosora?utm_source=appriver.jp&utm_medium=referral',
  },
  itsukakono: {
    title: 'いつかこの景色が思い出に変わる時',
    reading: 'いつかこのけしきがおもいでにかわるとき',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-12',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/itsukakono?utm_source=appriver.jp&utm_medium=referral',
  },
  konosakiga: {
    title: 'この先が見えなくなっても',
    reading: 'このさきがみえなくなっても',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-12',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/konosakiga?utm_source=appriver.jp&utm_medium=referral',
  },
  sonosakinimieru: {
    title: 'その先に見える未来',
    reading: 'そのさきにみえるみらい',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/sonosakinimieru?utm_source=appriver.jp&utm_medium=referral',
  },
  きせきがいまここにある: {
    title: '奇跡が今ここにある',
    reading: 'きせきがいまここにある',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/きせきがいまここにある?utm_source=appriver.jp&utm_medium=referral',
  },
  namidagakierusonohimade: {
    title: '涙が消えるその日まで',
    reading: 'なみだがきえるそのひまで',
    album: 'TOKOSHIE',
    albumReading: 'とこしえ',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namidagakierusonohimade?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 12,
  },
  futarinonagai: {
    title: '二人の長いストーリー',
    reading: 'ふたりのながいすとーりー',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/futarinonagai?utm_source=appriver.jp&utm_medium=referral',
  },
  bokunokaeru: {
    title: '僕の帰る場所',
    reading: 'ぼくのかえるばしょ',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-27',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/bokunokaeru?utm_source=appriver.jp&utm_medium=referral',
  },
  tanoshikattahibi: {
    title: '楽しかった日々',
    reading: 'たのしかったひび',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-27',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/tanoshikattahibi?utm_source=appriver.jp&utm_medium=referral',
  },
  kokorono: {
    title: '心の・・・',
    reading: 'こころの・・・',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-28',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kokorono?utm_source=appriver.jp&utm_medium=referral',
  },
  tsukamumiraimirai: {
    title: 'つかむ未来',
    reading: 'つかむみらい',
    album: '',
    albumReading: '',
    releaseDate: '2025-09-29',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/tsukamumiraimirai?utm_source=appriver.jp&utm_medium=referral',
  },
  hikarihaitsumokokoniaru: {
    title: '光はいつもここにある',
    reading: 'ひかりはいつもここにある',
    album: 'TOKOSHIE',
    albumReading: 'とこしえ',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/hikarihaitsumokokoniaru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 4,
  },
  deattekuretearigatou: {
    title: '出会ってくれてありがとう',
    reading: 'であってくれてありがとう',
    album: 'TOKOSHIE / KOMOREBI',
    albumReading: 'とこしえ / こもれび',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/deattekuretearigatou?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 14,
  },
  kagayaiteite: {
    title: '輝いていて',
    reading: 'かがやいていて',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kagayaiteite?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 14,
  },
  kiminotaisetsunahi: {
    title: '君の大切な日',
    reading: 'きみのたいせつなひ',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminotaisetsunahi?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 13,
  },
  aishitsuzukeru: {
    title: '愛し続ける',
    reading: 'あいしつづける',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/aishitsuzukeru?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 12,
  },
  itsumademoowaranai: {
    title: 'いつまでも終わらない',
    reading: 'いつまでもおわらない',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/itsumademoowaranai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 11,
  },
  subetenakushitemonao: {
    title: '全て無くしてもなお',
    reading: 'すべてなくしてもなお',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/subetenakushitemonao?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 10,
  },
  anohinikaeritai: {
    title: 'あの日に帰りたい',
    reading: 'あのひにかえりたい',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/anohinikaeritai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 9,
  },
  kimiwoomoidasudarou: {
    title: '君を思い出すだろう',
    reading: 'きみをおもいだすだろう',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kimiwoomoidasudarou?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 8,
  },
  kokorononaka: {
    title: '心の中',
    reading: 'こころのなか',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kokorononaka?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 7,
  },
  miraiwokaerukara: {
    title: '未来を変えるから',
    reading: 'みらいをかえるから',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/miraiwokaerukara?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 6,
  },
  kiminokiokugakierusonotokimadewa: {
    title: '君の記憶が消えるその時までは',
    reading: 'きみのきおくがきえるそのときまでは',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/kiminokiokugakierusonotokimadewa?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 5,
  },
  wasuretainoniwasurerarenai: {
    title: '忘れたいのに忘れられない',
    reading: 'わすれたいのにわすれられない',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/wasuretainoniwasurerarenai?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 4,
  },
  sobaniikuyo: {
    title: 'そばに行くよ',
    reading: 'そばにいくよ',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/sobaniikuyo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 3,
  },
  yumeoakiramenainaide: {
    title: '夢を諦めないで',
    reading: 'ゆめをあきらめないで',
    album: 'KOMOREBI',
    albumReading: 'こもれび',
    releaseDate: '2025-10-20',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/yumeoakiramenainaide?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 2,
  },
  namidademaegamienakunattemo: {
    title: '涙で前が見えなくなっても',
    reading: 'なみだでまえがみえなくなっても',
    album: 'TOKOSHIE / KOMOREBI',
    albumReading: 'とこしえ / こもれび',
    releaseDate: '2026-01-17',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/namidademaegamienakunattemo?utm_source=appriver.jp&utm_medium=referral',
    displayPriority: 7,
  },
  mataaou: {
    title: 'また逢おう',
    reading: 'またあおう',
    album: '',
    albumReading: '',
    releaseDate: '2025-10-04',
    linkUrl: 'https://mwm.ne.jp/artists/appriver/tracks/mataaou?utm_source=appriver.jp&utm_medium=referral',
  },
};

// 検索・ソート設定
const searchSortConfig = {
  defaultSort: 'releaseDate', // デフォルト: 新しい順（KOMOREBI内はdisplayPriorityで固定）
  defaultOrder: 'desc', // デフォルト順序（優先度の高い=新規追加が先頭）
  searchFields: ['title', 'album'], // 検索対象フィールド
  itemsPerPage: 20, // 最大表示件数
};

// 楽曲データ配列取得関数
function getSongsArray() {
  return Object.entries(songsData).map(([id, data]) => ({
    id,
    ...data,
  }));
}

// デフォルトエクスポート（モジュール対応）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { songsData, searchSortConfig, getSongsArray };
}
