// KOMOREBI 15曲 追加用テンプレート（songs-data.js へ貼り付け）
// - ID命名: 英小文字+数字。例: komorebi01 ～ komorebi15（仮）
// - アルバム表記: album は 'KOMOREBI'、albumReading は 'こもれび'
// - 日付: '2025-10-20'（アルバム配信日）
// - リンク: '/out/komorebi'（正式URL確定後に置換）
// - 歌詞: バッククォート`を含めないこと（テンプレートリテラルのため）

/*
komorebi01: {
  title: '（曲名01）',
  reading: '（よみ01）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi02: {
  title: '（曲名02）',
  reading: '（よみ02）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi03: {
  title: '（曲名03）',
  reading: '（よみ03）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi04: {
  title: '（曲名04）',
  reading: '（よみ04）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi05: {
  title: '（曲名05）',
  reading: '（よみ05）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi06: {
  title: '（曲名06）',
  reading: '（よみ06）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi07: {
  title: '（曲名07）',
  reading: '（よみ07）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi08: {
  title: '（曲名08）',
  reading: '（よみ08）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi09: {
  title: '（曲名09）',
  reading: '（よみ09）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi10: {
  title: '（曲名10）',
  reading: '（よみ10）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi11: {
  title: '（曲名11）',
  reading: '（よみ11）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi12: {
  title: '（曲名12）',
  reading: '（よみ12）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi13: {
  title: '（曲名13）',
  reading: '（よみ13）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi14: {
  title: '（曲名14）',
  reading: '（よみ14）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
komorebi15: {
  title: '（曲名15）',
  reading: '（よみ15）',
  album: 'KOMOREBI',
  albumReading: 'こもれび',
  releaseDate: '2025-10-20',
  linkUrl: '/out/komorebi',
  lyrics: `歌詞準備中`,
},
*/
