name: CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps (ci)
        run: npm ci

      - name: Build (if present)
        run: npm run build --if-present

      - name: Syntax check songs-data.js (ESM import)
        run: node --input-type=module -e "import('./songs-data.js').then(()=>console.log('syntax ok')).catch(e=>{console.error(e); process.exit(1);})"
